apiVersion: v1
kind: Service
metadata:
  namespace: orihime
  name: orihime-beta-web
spec:
  selector:
    app: orihime-beta
  ports:
  - name: hunchentoot
    protocol: TCP
    port: 80
    targetPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  namespace: orihime
  name: orihime-beta-sbcl
spec:
  type: NodePort
  selector:
    app: orihime-beta
  ports:
  - name: slime-through-nginx
    protocol: TCP
    port: 4006
    targetPort: 4006
    nodePort: 30006
