apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: NodePort
  clusterIP: 10.100.108.213
  selector:
    app: registry
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30005
