apiVersion: v1
kind: Service
metadata:
  name: registry
  annotations:
    haproxy.org/load-balance: "leastconn"
    haproxy.org/pod-maxconn: "50"
spec:
  clusterIP: 10.100.108.213
  selector:
    app: registry
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
