apiVersion: v1
kind: PersistentVolume
metadata:
  name: orihime-beta-mysql-volume
  namespace: orihime
  labels: 
    orihime-beta-mysql-volume: "true"
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /exports/orihime/beta/mysql
    server: 192.155.80.87 # The master
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orihime-beta-mysql-volume-claim
  namespace: orihime
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow
  selector:
    matchLabels:
      orihime-beta-mysql-volume: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orihime-beta-mysql
  namespace: orihime
  labels:
    app: orihime-beta-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orihime-beta-mysql
  template:
    metadata:
      labels:
        app: orihime-beta-mysql
    spec:
      imagePullSecrets:
        - name: container-registry-dacodastrack-com-secret
      containers:
      - name: mysql
        image: container-registry.dacodastrack.com/orihime-mysql:beta
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        envFrom:
          - secretRef:
              name: orihime-beta-mysql
        volumeMounts:
        - mountPath: /var/lib/orihime/mysql/
          name: orihime-beta-mysql
        - mountPath: /docker-entrypoint-initdb.d/initialize-orihime-user.sql
          name: orihime-beta-mysql-initialize-user
          subPath: initialize-orihime-user.sql
      volumes:
      - name: orihime-beta-mysql
        persistentVolumeClaim:
          claimName: orihime-beta-mysql-volume-claim
      - name: orihime-beta-mysql-initialize-user
        secret:
          secretName: orihime-beta-mysql-initialize-user
--- 
apiVersion: v1
kind: Service
metadata:
  namespace: orihime
  name: orihime-beta-mysql
spec:
  selector:
    app: orihime-beta-mysql
  ports:
  - name: orihime-beta-mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
