apiVersion: apps/v1
kind: Deployment
metadata:
  name: orihime-beta
  namespace: orihime
  labels:
    app: orihime-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orihime-beta
  template:
    metadata:
      labels:
        app: orihime-beta
    spec:
      imagePullSecrets:
        - name: container-registry-dacodastrack-com-secret
      containers:
      - name: sbcl
        image: container-registry.dacodastrack.com/orihime-sbcl:beta
        imagePullPolicy: Always
        ports:
        - containerPort: 4005
          containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        envFrom:
          - secretRef:
              name: orihime-beta-mysql
        volumeMounts:
        - mountPath: /var/lib/goo/data/dictionary-entries
          name: orihime-goo
      - name: nginx
        image: nginx
        command: ["nginx-debug", "-g", "daemon off;"]
        ports:
        - containerPort: 4006
        volumeMounts:
          - mountPath: /etc/nginx/ssl/k8s
            name: nginx-tls
          - mountPath: /etc/nginx/ssl/certs
            name: nginx-trusted-ca
          - mountPath: /etc/nginx/nginx.conf
            name: nginx-conf
            subPath: nginx.conf
      - name: goo-local
        image: container-registry.dacodastrack.com/goo-local:beta
        imagePullPolicy: Always
        ports:
        - containerPort: 7081
      volumes:
      - name: orihime-beta-mysql
        hostPath:
          path: /var/lib/orihime/mysql/
      - name: orihime-goo
        hostPath:
          path: /var/lib/orihime/goo-local/dictionary/
      - name: nginx-tls
        secret:
          secretName: tls-secret
      - name: nginx-trusted-ca
        secret:
          secretName: trusted-ca
      - name: nginx-conf
        secret:
          secretName: beta-nginx-conf
          
