apiVersion: apps/v1
kind: Deployment
metadata:
  name: orihime
  namespace: orihime
  labels:
    app: orihime-alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orihime-alpha
  template:
    metadata:
      labels:
        app: orihime-alpha
    spec:
      imagePullSecrets:
        - name: container-registry-dacodastrack-com-secret
      containers:
      - name: sbcl
        image: container-registry.dacodastrack.com/orihime-sbcl:alpha
        imagePullPolicy: Always
        ports:
        - containerPort: 4005
          containerPort: 80
        envFrom:
          - secretRef:
              name: orihime-alpha-mysql
        volumeMounts:
        - mountPath: /var/lib/goo/data/dictionary-entries
          name: orihime-goo
      - name: nginx
        image: nginx
        command: ["nginx-debug", "-g", "daemon off;"]
        ports:
        - containerPort: 4006
        volumeMounts:
          - mountPath: /etc/nginx/ssl/k8s
            name: nginx-tls
          - mountPath: /etc/nginx/ssl/certs
            name: nginx-trusted-ca
          - mountPath: /etc/nginx/nginx.conf
            name: nginx-conf
            subPath: nginx.conf
      - name: goo-local
        image: container-registry.dacodastrack.com/goo-local:alpha
        imagePullPolicy: Always
        ports:
        - containerPort: 7081
      - name: mysql
        image: container-registry.dacodastrack.com/orihime-mysql:alpha
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        envFrom:
          - secretRef:
              name: orihime-alpha-mysql
        volumeMounts:
        - mountPath: /var/lib/orihime/mysql/
          name: orihime-alpha-mysql
      volumes:
      - name: orihime-alpha-mysql
        hostPath:
          path: /var/lib/orihime/mysql/
      - name: orihime-goo
        hostPath:
          path: /var/lib/orihime/goo-local/dictionary/
      - name: nginx-tls
        secret:
          secretName: tls-secret
      - name: nginx-trusted-ca
        secret:
          secretName: alpha-trusted-ca
      - name: nginx-conf
        secret:
          secretName: alpha-nginx-conf
          
